#!/usr/bin/env python3
"""Cache the exact bundle text the platform published, per Definition module.

WHY
---
`build_published_mirror.py` copies bundles out of the local `Definitions/` tree.
That is the wrong source for a *published* bundle. The local file may have been
regenerated by `wave_generate.py` since, and a regenerated bundle emits imports
for whatever the local decl graph says, which is not what was published. The
observed symptom was a mirror full of missing-olean cascades that said nothing
about the platform: `Def_ChapterQgBrstDerivativeGauge` locally imports
`Def_ChapterQgContinuumModeInstance`, whose platform status is FAILED, yet the
bundle is published -- so the published text cannot contain that import.

`GET /publish-jobs?kind=definition` returns every publish job, and each job
carries the source that was submitted in its `definitions` field. Newest job per
`theorem_name` wins (a later FAILED job does not revoke an earlier PUBLISHED one,
matching platform_def_index.py).

OUTPUT
------
    state/published_bundles/Def_<chapter>.lean   published text, verbatim
    state/published_bundles/manifest.json        {"chapter": {"status","lines","sha"}}

Nothing here uploads; this is a read-only sync plus a disk cache.

USAGE
-----
    PROVE2ME_WS=<workspace> python3 debug/cache_published_bundles.py
    PROVE2ME_WS=<workspace> python3 debug/cache_published_bundles.py --report
"""
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WS = os.environ.get("PROVE2ME_WS") or os.path.dirname(HERE)
sys.path.insert(0, f"{WS}/pipeline")

import upload_pipeline as up  # noqa: E402

OUT = f"{WS}/state/published_bundles"
MANIFEST = f"{OUT}/manifest.json"


def newest_jobs():
    jobs = up._paged("publish-jobs", {"kind": "definition"})
    newest = {}
    for j in jobs:
        name = j.get("theorem_name") or ""
        if not name:
            continue
        stamp = j.get("updated_at") or j.get("created_at") or ""
        prev = newest.get(name)
        if prev is None or (prev.get("updated_at") or prev.get("created_at") or "") <= stamp:
            newest[name] = j
    return newest


def text_of(job):
    text = job.get("definitions") or ""
    if not isinstance(text, str):
        text = json.dumps(text)
    return text


def refresh():
    newest = newest_jobs()
    if not newest:
        print("no definition publish jobs returned", file=sys.stderr)
        return 1
    os.makedirs(OUT, exist_ok=True)
    manifest = {}
    written = skipped = 0
    for name, j in sorted(newest.items()):
        if j.get("status") != "PUBLISHED":
            continue
        text = text_of(j)
        if not text.strip():
            skipped += 1
            continue
        path = f"{OUT}/Def_{name}.lean"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text if text.endswith("\n") else text + "\n")
        manifest[name] = {
            "status": "PUBLISHED",
            "lines": text.count("\n") + 1,
            "sha": hashlib.sha256(text.encode("utf-8")).hexdigest()[:16],
        }
        written += 1
    with open(MANIFEST, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=1, sort_keys=True)
    print(f"cached {written} published bundle(s) to {OUT}"
          + (f"; {skipped} had empty text" if skipped else ""))
    return 0


def report():
    """Compare the published text against the local file, per bundle."""
    if not os.path.exists(MANIFEST):
        print("no cache; run without --report first", file=sys.stderr)
        return 1
    manifest = json.load(open(MANIFEST))
    same = drift = absent = 0
    drifted = []
    for name in sorted(manifest):
        pub = f"{OUT}/Def_{name}.lean"
        loc = f"{WS}/Definitions/Def_{name}.lean"
        if not os.path.exists(loc):
            absent += 1
            continue
        a = open(pub, encoding="utf-8").read()
        b = open(loc, encoding="utf-8").read()
        if a.strip() == b.strip():
            same += 1
        else:
            drift += 1
            drifted.append(name)
    print(f"identical to local : {same}")
    print(f"drifted from local : {drift}")
    print(f"no local file      : {absent}")
    for n in drifted[:15]:
        print(f"   drift: {n}")
    return 0


if __name__ == "__main__":
    if "--report" in sys.argv:
        sys.exit(report())
    sys.exit(refresh())