#!/usr/bin/env python3
"""Cache the exact bundle text the platform published, per Definition module.

WHY
---
`build_published_mirror.py` copies bundles out of the local `Definitions/` tree.
That is the wrong source for a *published* bundle. The local file may have been
regenerated by `wave_generate.py` since, and a regenerated bundle emits imports
for whatever the local decl graph says, which is not what was published. The
observed symptom was a mirror full of missing-olean cascades that said nothing
about the platform: `Def_ChapterQgBrstDerivativeGauge` locally imports
`Def_ChapterQgContinuumModeInstance`, whose platform status is FAILED, yet the
bundle is published -- so the published text cannot contain that import.

`GET /publish-jobs?kind=definition` returns every publish job, and each job
carries the source that was submitted in its `definitions` field. Newest job per
`theorem_name` wins (a later FAILED job does not revoke an earlier PUBLISHED one,
matching platform_def_index.py).

OUTPUT
------
    state/published_bundles/Def_<chapter>.lean   published text, verbatim
    state/published_bundles/manifest.json        {"chapter": {"status","lines","sha"}}

Nothing here uploads; this is a read-only sync plus a disk cache.

USAGE
-----
    PROVE2ME_WS=<workspace> python3 debug/cache_published_bundles.py
    PROVE2ME_WS=<workspace> python3 debug/cache_published_bundles.py --report
"""
import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WS = os.environ.get("PROVE2ME_WS") or os.path.dirname(HERE)
sys.path.insert(0, f"{WS}/pipeline")

import upload_pipeline as up  # noqa: E402

OUT = f"{WS}/state/published_bundles"
MANIFEST = f"{OUT}/manifest.json"
THM_OUT = f"{WS}/state/published_theorems"
THM_MANIFEST = f"{THM_OUT}/manifest.json"
THEOREM_IMPORT = re.compile(r"^import\s+Theorems\.(Thm_\S+)", re.M)


def needed_theorem_modules():
    """Which `Theorems.*` modules do the published bundles actually import?

    Only a handful do. Caching all ~5.8k published problem jobs would be wasteful
    and most of them are stubs nobody imports, so drive this off the published
    def bundles' own import lines."""
    need = {}
    if not os.path.isdir(OUT):
        return need
    for f in sorted(os.listdir(OUT)):
        if not (f.startswith("Def_") and f.endswith(".lean")):
            continue
        text = open(f"{OUT}/{f}", encoding="utf-8").read()
        for mod in THEOREM_IMPORT.findall(text):
            need[mod] = f[len("Def_"):-len(".lean")]
    return need


def module_name(theorem_name):
    """`BookProof.Qg.foo_bar` -> `Thm_BookProof_Qg_foo_bar`.

    This is the module the def bundles import, so the mapping has to match the
    platform's own sanitisation rather than anything derived locally."""
    return "Thm_" + re.sub(r"[^A-Za-z0-9_]", "_", theorem_name)


def refresh_theorems():
    """Cache the published source of every `Theorems.*` module a published def
    bundle imports. Read-only: a problem job's `definitions` field is the module
    the platform published, which for a problem is a generated stub."""
    need = needed_theorem_modules()
    if not need:
        print("no published bundle imports a Theorems module")
        return 0
    jobs = up._paged("publish-jobs", {"kind": "problem"})
    if not jobs:
        print("no problem publish jobs returned", file=sys.stderr)
        return 1
    newest = {}
    for j in jobs:
        name = j.get("theorem_name") or ""
        if not name:
            continue
        stamp = j.get("updated_at") or j.get("created_at") or ""
        prev = newest.get(name)
        if prev is None or (prev.get("updated_at") or prev.get("created_at") or "") <= stamp:
            newest[name] = j
    by_module = {}
    for name, j in newest.items():
        if j.get("status") == "PUBLISHED":
            by_module[module_name(name)] = j
    os.makedirs(THM_OUT, exist_ok=True)
    manifest, missing = {}, []
    for mod, importer in sorted(need.items()):
        j = by_module.get(mod)
        if j is None:
            missing.append((mod, importer))
            continue
        text = text_of(j)
        if not text.strip():
            missing.append((mod, importer))
            continue
        with open(f"{THM_OUT}/{mod}.lean", "w", encoding="utf-8") as fh:
            fh.write(text if text.endswith("\n") else text + "\n")
        manifest[mod] = {
            "imported_by": importer,
            "theorem_name": j.get("theorem_name"),
            "lines": text.count("\n") + 1,
            "sha": hashlib.sha256(text.encode("utf-8")).hexdigest()[:16],
        }
    with open(THM_MANIFEST, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=1, sort_keys=True)
    print(f"needed {len(need)} Theorems module(s); cached {len(manifest)}")
    for mod, importer in missing:
        print(f"   MISSING {mod}  (imported by {importer})")
    return 0 if not missing else 0


def newest_jobs():
    jobs = up._paged("publish-jobs", {"kind": "definition"})
    # Newest job per name wins, EXCEPT that a FAILED job must not revoke an
    # older PUBLISHED one, and the page order is not chronological. Track the
    # newest PUBLISHED job separately and let it win. Without this,
    # ChapterYangMillsSU3 (one PUBLISHED job, three later "already exists"
    # failures) was withheld from the cache, and every bundle importing it
    # cascaded.
    newest = {}
    newest_pub = {}
    for j in jobs:
        name = j.get("theorem_name") or ""
        if not name:
            continue
        stamp = j.get("updated_at") or j.get("created_at") or ""
        prev = newest.get(name)
        if prev is None or (prev.get("updated_at") or prev.get("created_at") or "") <= stamp:
            newest[name] = j
        if j.get("status") == "PUBLISHED":
            pp = newest_pub.get(name)
            if pp is None or (pp.get("updated_at") or pp.get("created_at") or "") <= stamp:
                newest_pub[name] = j
    for name, j in newest_pub.items():
        newest[name] = j
    return newest


def text_of(job):
    text = job.get("definitions") or ""
    if not isinstance(text, str):
        text = json.dumps(text)
    return text


def refresh():
    newest = newest_jobs()
    if not newest:
        print("no definition publish jobs returned", file=sys.stderr)
        return 1
    os.makedirs(OUT, exist_ok=True)
    manifest = {}
    written = skipped = 0
    for name, j in sorted(newest.items()):
        if j.get("status") != "PUBLISHED":
            continue
        text = text_of(j)
        if not text.strip():
            skipped += 1
            continue
        path = f"{OUT}/Def_{name}.lean"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text if text.endswith("\n") else text + "\n")
        manifest[name] = {
            "status": "PUBLISHED",
            "lines": text.count("\n") + 1,
            "sha": hashlib.sha256(text.encode("utf-8")).hexdigest()[:16],
        }
        written += 1
    with open(MANIFEST, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=1, sort_keys=True)
    print(f"cached {written} published bundle(s) to {OUT}"
          + (f"; {skipped} had empty text" if skipped else ""))
    return 0


def report():
    """Compare the published text against the local file, per bundle."""
    if not os.path.exists(MANIFEST):
        print("no cache; run without --report first", file=sys.stderr)
        return 1
    manifest = json.load(open(MANIFEST))
    same = drift = absent = 0
    drifted = []
    for name in sorted(manifest):
        pub = f"{OUT}/Def_{name}.lean"
        loc = f"{WS}/Definitions/Def_{name}.lean"
        if not os.path.exists(loc):
            absent += 1
            continue
        a = open(pub, encoding="utf-8").read()
        b = open(loc, encoding="utf-8").read()
        if a.strip() == b.strip():
            same += 1
        else:
            drift += 1
            drifted.append(name)
    print(f"identical to local : {same}")
    print(f"drifted from local : {drift}")
    print(f"no local file      : {absent}")
    for n in drifted[:15]:
        print(f"   drift: {n}")
    return 0


if __name__ == "__main__":
    if "--report" in sys.argv:
        sys.exit(report())
    if "--theorems" in sys.argv:
        sys.exit(refresh_theorems())
    rc = refresh()
    sys.exit(rc)