name = "prove2me_workspace"
version = "0.1.0"
defaultTargets = ["Definitions"]

[[lean_lib]]
name = "Definitions"

[[lean_lib]]
name = "Theorems"

[[lean_lib]]
name = "Solutions"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "0df444a360eaa60ab8c11dca51a86af692955474"
