-- Generated from ChapterHashimotoShiftInvert.lean — solution of BookProof.HashimotoShiftInvert.ell2UnboundedExample_isShiftInvert
import Mathlib
import Definitions.Def_ChapterHashimotoShiftInvert
import Theorems.Thm_BookProof_HashimotoShiftInvert_isShiftInvert_invShiftOperator
import Theorems.Thm_ell2ShiftInvert_injective
open BookProof.HashimotoShiftInvert




open BookProof.FarisLavine BookProof.YangMillsFriedrichs BookProof.YangMillsFriedrichsLimit
open BookProof.HermiteGalerkin
open Filter Topology

set_option maxHeartbeats 1000000 in
theorem solution :
    IsShiftInvert ell2UnboundedExample 1 ell2ShiftInvert := isShiftInvert_invShiftOperator ell2ShiftInvert ell2ShiftInvert_injective 1
