import Theorems.Thm_BookProof_ChapterStoneResolvent_UnboundedSelfAdjoint_norm_approxU_sub_apply_le

import Theorems.Thm_BookProof_ChapterStoneResolvent_UnboundedSelfAdjoint_yosida_tendsto

import Theorems.Thm_BookProof_ChapterStoneResolvent_UnboundedSelfAdjoint_norm_approxU_apply


import Definitions.Def_ChapterStoneEvolution
import Mathlib


/-!
# The general Stone theorem, part IV: the group `e^{-itA}` and its continuity

The approximating groups `e^{-itA_n}` converge strongly; the limit `U t = e^{-itA}` is
constructed here and shown to be a strongly continuous one-parameter unitary group.
-/

open scoped InnerProductSpace
open Filter Topology NormedSpace

namespace BookProof.ChapterStoneResolvent

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

omit [CompleteSpace H] in
/-- A sequence of isometric operators which converges pointwise on a dense set converges
pointwise everywhere (Cauchy version). -/
theorem cauchySeq_of_dense_of_isometry {F : ℕ → H →L[ℂ] H} (hiso : ∀ k y, ‖F k y‖ = ‖y‖)
    {D : Set H} (hD : Dense D) (hC : ∀ y ∈ D, CauchySeq (fun k => F k y)) (y : H) :
    CauchySeq (fun k => F k y) := by
  rw [Metric.cauchySeq_iff]
  intro ε hε
  obtain ⟨z, hz, hyz⟩ := hD.exists_dist_lt y (ε := ε / 3) (by linarith)
  obtain ⟨N, hN⟩ := Metric.cauchySeq_iff.mp (hC z hz) (ε / 3) (by linarith)
  refine ⟨N, fun k hk l hl => ?_⟩
  have hkz : dist (F k y) (F k z) = dist y z := by
    rw [dist_eq_norm, dist_eq_norm, ← map_sub, hiso]
  have hlz : dist (F l z) (F l y) = dist y z := by
    rw [dist_eq_norm, dist_eq_norm, ← map_sub, hiso, norm_sub_rev]
  calc dist (F k y) (F l y)
      ≤ dist (F k y) (F k z) + dist (F k z) (F l z) + dist (F l z) (F l y) :=
        dist_triangle4 _ _ _ _
    _ < ε / 3 + ε / 3 + ε / 3 := by
        rw [hkz, hlz]
        have := hN k hk l hl
        linarith
    _ = ε := by ring

namespace UnboundedSelfAdjoint

variable (T : UnboundedSelfAdjoint H)

/-! ## Strong convergence of the approximations -/

theorem approxU_cauchy_domain (t : ℝ) (x : T.domain) :
    CauchySeq (fun k : ℕ => T.approxU ((k : ℝ) + 1) t (x : H)) := by
  have hy : CauchySeq (fun k : ℕ => T.yosida ((k : ℝ) + 1) (x : H)) :=
    (T.yosida_tendsto x).cauchySeq
  rw [Metric.cauchySeq_iff]
  intro ε hε
  have hpos : (0 : ℝ) < ε / (|t| + 1) := by positivity
  obtain ⟨N, hN⟩ := Metric.cauchySeq_iff.mp hy _ hpos
  refine ⟨N, fun k hk l hl => ?_⟩
  have hkl := hN k hk l hl
  rw [dist_eq_norm] at hkl ⊢
  have hbound := T.norm_approxU_sub_apply_le ((k : ℝ) + 1) ((l : ℝ) + 1) t (x : H)
  have habs : (0 : ℝ) ≤ |t| := abs_nonneg t
  calc ‖T.approxU ((k : ℝ) + 1) t (x : H) - T.approxU ((l : ℝ) + 1) t (x : H)‖
      ≤ |t| * ‖T.yosida ((k : ℝ) + 1) (x : H) - T.yosida ((l : ℝ) + 1) (x : H)‖ := hbound
    _ ≤ |t| * (ε / (|t| + 1)) := by
        exact mul_le_mul_of_nonneg_left (le_of_lt hkl) habs
    _ < ε := by
        rw [mul_div_assoc'] at *
        rw [div_lt_iff₀ (by positivity)]
        nlinarith

theorem approxU_cauchy (t : ℝ) (x : H) :
    CauchySeq (fun k : ℕ => T.approxU ((k : ℝ) + 1) t x) := by
  refine cauchySeq_of_dense_of_isometry (F := fun k => T.approxU ((k : ℝ) + 1) t)
    (fun k y => T.norm_approxU_apply _ t y) T.denseDomain ?_ x
  intro y hy
  exact T.approxU_cauchy_domain t ⟨y, hy⟩

/-! ## The limit group -/

/-- The unitary group `e^{-itA}` generated by the self-adjoint operator `A`, defined as the
strong limit of `e^{-itA_n}`. -/
noncomputable def stoneFun (t : ℝ) (x : H) : H :=
  limUnder atTop (fun k : ℕ => T.approxU ((k : ℝ) + 1) t x)

theorem tendsto_stoneFun (t : ℝ) (x : H) :
    Tendsto (fun k : ℕ => T.approxU ((k : ℝ) + 1) t x) atTop (𝓝 (T.stoneFun t x)) := by
  obtain ⟨z, hz⟩ := cauchySeq_tendsto_of_complete (T.approxU_cauchy t x)
  rw [stoneFun, hz.limUnder_eq]
  exact hz

theorem norm_stoneFun (t : ℝ) (x : H) : ‖T.stoneFun t x‖ = ‖x‖ := by
  have h1 : Tendsto (fun k : ℕ => ‖T.approxU ((k : ℝ) + 1) t x‖) atTop (𝓝 ‖T.stoneFun t x‖) :=
    (T.tendsto_stoneFun t x).norm
  have h2 : (fun k : ℕ => ‖T.approxU ((k : ℝ) + 1) t x‖) = fun _ : ℕ => ‖x‖ := by
    funext k; exact T.norm_approxU_apply _ t x
  rw [h2] at h1
  exact tendsto_nhds_unique h1 tendsto_const_nhds

/-- `e^{-itA}` as a linear map. -/
noncomputable def stoneLinear (t : ℝ) : H →ₗ[ℂ] H where
  toFun x := T.stoneFun t x
  map_add' x y := by
    refine tendsto_nhds_unique (T.tendsto_stoneFun t (x + y)) ?_
    have h : (fun k : ℕ => T.approxU ((k : ℝ) + 1) t (x + y))
        = fun k : ℕ => T.approxU ((k : ℝ) + 1) t x + T.approxU ((k : ℝ) + 1) t y := by
      funext k; rw [map_add]
    rw [h]
    exact (T.tendsto_stoneFun t x).add (T.tendsto_stoneFun t y)
  map_smul' c x := by
    refine tendsto_nhds_unique (T.tendsto_stoneFun t (c • x)) ?_
    have h : (fun k : ℕ => T.approxU ((k : ℝ) + 1) t (c • x))
        = fun k : ℕ => c • T.approxU ((k : ℝ) + 1) t x := by
      funext k; rw [map_smul]
    rw [h]
    exact (T.tendsto_stoneFun t x).const_smul c

/-- **The unitary group `e^{-itA}`** generated by an unbounded self-adjoint operator. -/
noncomputable def stoneU (t : ℝ) : H →L[ℂ] H :=
  (T.stoneLinear t).mkContinuous 1 (fun x => by
    simp only [stoneLinear, LinearMap.coe_mk, AddHom.coe_mk, one_mul]
    exact le_of_eq (T.norm_stoneFun t x))

















/-! ## Strong continuity -/















end UnboundedSelfAdjoint

end BookProof.ChapterStoneResolvent
