import Definitions.Def_ChapterAbelianCyclicModel
import Definitions.Def_ChapterAbelianGelfandModel
import Mathlib


/-!
# Abelian algebras without a cyclic vector: the direct-sum model (plan GAP-2)

`ChapterAbelianCyclicModel` models an **arbitrary** abelian algebra — a unital
`*`-representation `π : C(X, ℂ) →⋆ₐ[ℂ] (H →L[ℂ] H)` of the continuous functions on a
compact Hausdorff space — **with a cyclic unit vector**, as multiplication operators
on `L²(μ)`.  This module removes the cyclic-vector hypothesis, exactly as
`ChapterCyclicDecomposition` / `ChapterCyclicDirectSum` / `ChapterSpectralDirectSum`
do for the algebra generated by a single normal operator, but now for a whole
abelian algebra at once.

* `repCyclicSubspace` — the closed subspace generated by `{π(f)ξ}`;
  `RepInvariant`, `repInvariant_repCyclicSubspace`, `repInvariant_orthogonal`
  (the `*`-closedness of the algebra makes the orthogonal complement of an invariant
  subspace invariant), `repCyclicSubspace_le_orthogonal`;
* `exists_rep_cyclic_decomposition` — by Zorn's lemma a family of unit vectors whose
  cyclic subspaces are pairwise orthogonal and jointly dense;
* `orthogonalFamily_repCyclicSubspace`, `isHilbertSum_repCyclicSubspace`,
  `exists_isHilbertSum_repCyclicSubspace` — the space *is* the Hilbert sum of those
  subspaces; `starProjection_commutes_rep` — the projections onto the summands lie in
  the commutant of the algebra;
* `repCyclicUnitary`, `repEmbedding`, `range_repEmbedding`,
  `repEmbedding_intertwines` — the model of a summand, built inside the ambient
  space: an isometric embedding of `L²(μ_ξ)` with range the cyclic subspace of `ξ`,
  carrying multiplication by every continuous symbol `g` into `π(g)`;
* HEADLINE `abelian_multiplication_model_general` — **every** unital
  `*`-representation of `C(X, ℂ)` on a complex Hilbert space is a direct sum of
  multiplication representations: there are Borel probability measures `μₓ` on `X`
  and isometric embeddings `Vₓ : L²(μₓ) → H` exhibiting `H` as their Hilbert sum,
  with `π(g)` acting on each summand as multiplication by `g`.  No cyclic vector, no
  generator and no separability are assumed;
* `abelian_multiplication_model_separable` — on a separable space the family is
  countable;
* `abelian_algebra_multiplication_model_general` — the Gelfand form, for a
  representation of an abstract commutative unital C\*-algebra.

Everything is `sorry`-free and `axiom`-free.
-/

noncomputable section

open MeasureTheory Complex WeakDual

namespace BookProof.ChapterAbelianDirectSum

open BookProof.ChapterAbelianGelfandModel BookProof.ChapterAbelianCyclicModel

variable {X : Type*} [TopologicalSpace X] [CompactSpace X] [T2Space X]
  [MeasurableSpace X] [BorelSpace X]
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (pi : C(X, ℂ) →⋆ₐ[ℂ] (H →L[ℂ] H))

/-! ## 1. Cyclic subspaces of a representation -/

/-- **The cyclic subspace generated by a vector**: the closed linear span of the
vectors `π(f)ξ`, `f` continuous on `X`. -/
def repCyclicSubspace (xi : H) : Submodule ℂ H :=
  (Submodule.span ℂ (Set.range fun g : C(X, ℂ) => pi g xi)).topologicalClosure

omit [CompactSpace X] [T2Space X] [MeasurableSpace X] [BorelSpace X] in
theorem isClosed_repCyclicSubspace (xi : H) :
    IsClosed (repCyclicSubspace pi xi : Set H) :=
  Submodule.isClosed_topologicalClosure _

omit [CompactSpace X] [T2Space X] [MeasurableSpace X] [BorelSpace X] in
theorem rep_apply_mem_repCyclicSubspace (xi : H) (g : C(X, ℂ)) :
    pi g xi ∈ repCyclicSubspace pi xi :=
  Submodule.le_topologicalClosure _ (Submodule.subset_span ⟨g, rfl⟩)



/-! ## 2. Invariance -/

/-- A subspace invariant under the whole represented algebra. -/
def RepInvariant (M : Submodule ℂ H) : Prop :=
  ∀ (g : C(X, ℂ)) (v : H), v ∈ M → pi g v ∈ M







/-! ## 3. The decomposition -/

/-- A set of unit vectors with pairwise orthogonal cyclic subspaces. -/
def OrthogonalRepCyclicFamily (S : Set H) : Prop :=
  (∀ x ∈ S, ‖x‖ = 1) ∧
    ∀ x ∈ S, ∀ y ∈ S, x ≠ y → repCyclicSubspace pi x ≤ (repCyclicSubspace pi y)ᗮ





/-! ## 4. The Hilbert sum -/

instance instCompleteSpaceRepCyclicSubspace (xi : H) :
    CompleteSpace (repCyclicSubspace pi xi) :=
  (isClosed_repCyclicSubspace pi xi).completeSpace_coe

omit [CompactSpace X] [T2Space X] [MeasurableSpace X] [BorelSpace X] in
theorem orthogonalFamily_repCyclicSubspace {S : Set H} (hS : OrthogonalRepCyclicFamily pi S) :
    OrthogonalFamily ℂ (fun x : S => (repCyclicSubspace pi (x : H)))
      (fun x : S => (repCyclicSubspace pi (x : H)).subtypeₗᵢ) := by
  refine OrthogonalFamily.of_pairwise ?_
  intro x y hxy
  refine Submodule.isOrtho_iff_le.2 ?_
  exact hS.2 (x : H) x.2 (y : H) y.2 (Subtype.coe_injective.ne hxy)

omit [CompactSpace X] [T2Space X] [MeasurableSpace X] [BorelSpace X] in
/-- **`H` is the Hilbert sum of the cyclic subspaces** of a total orthogonal cyclic
family. -/
theorem isHilbertSum_repCyclicSubspace {S : Set H} (hS : OrthogonalRepCyclicFamily pi S)
    (htop : (⨆ x ∈ S, repCyclicSubspace pi x).topologicalClosure = ⊤) :
    IsHilbertSum ℂ (fun x : S => (repCyclicSubspace pi (x : H)))
      (fun x : S => (repCyclicSubspace pi (x : H)).subtypeₗᵢ) := by
  refine IsHilbertSum.mkInternal _ (orthogonalFamily_repCyclicSubspace pi hS) ?_
  have hsup : (⨆ x : S, repCyclicSubspace pi (x : H)) = ⨆ x ∈ S, repCyclicSubspace pi x := by
    rw [iSup_subtype]
  rw [hsup, htop]

/-- The unitary identification of `H` with the `ℓ²`-sum of the cyclic subspaces. -/
def repCyclicHilbertEquiv {S : Set H} (hS : OrthogonalRepCyclicFamily pi S)
    (htop : (⨆ x ∈ S, repCyclicSubspace pi x).topologicalClosure = ⊤) :
    H ≃ₗᵢ[ℂ] lp (fun x : S => (repCyclicSubspace pi (x : H))) 2 :=
  (isHilbertSum_repCyclicSubspace pi hS htop).linearIsometryEquiv







/-! ## 5. The model of a summand, built inside the ambient space -/

variable (xi : H)

omit [T2Space X] [MeasurableSpace X] [BorelSpace X] in
theorem repCyclicSubspace_eq_closure_range :
    (repCyclicSubspace pi xi : Set H) = closure (Set.range (repVec pi xi)) := by
  have hrange : (Set.range fun g : C(X, ℂ) => pi g xi) = Set.range (repVec pi xi) := rfl
  have hspan : Submodule.span ℂ (Set.range fun g : C(X, ℂ) => pi g xi)
      = LinearMap.range (repVec pi xi) := by
    rw [hrange, ← LinearMap.coe_range, Submodule.span_eq]
  rw [repCyclicSubspace, hspan]
  exact Submodule.topologicalClosure_coe _

/-- The generating map `f ↦ π(f)ξ`, seen as a map into the cyclic subspace of `ξ`. -/
def repVecTo : C(X, ℂ) →ₗ[ℂ] repCyclicSubspace pi xi :=
  LinearMap.codRestrict _ (repVec pi xi) (rep_apply_mem_repCyclicSubspace pi xi)

omit [T2Space X] [MeasurableSpace X] [BorelSpace X] in
@[simp] theorem repVecTo_apply (f : C(X, ℂ)) : (repVecTo pi xi f : H) = pi f xi := rfl

omit [T2Space X] [MeasurableSpace X] [BorelSpace X] in
theorem denseRange_repVecTo : DenseRange (repVecTo pi xi) := by
  change Dense (Set.range (repVecTo pi xi))
  rw [Topology.IsInducing.subtypeVal.dense_iff]
  intro m
  have hm : (m : H) ∈ closure (Set.range (repVec pi xi)) := by
    rw [← repCyclicSubspace_eq_closure_range]
    exact m.2
  refine closure_mono ?_ hm
  rintro _ ⟨f, rfl⟩
  exact ⟨repVecTo pi xi f, ⟨f, rfl⟩, rfl⟩

/-- **The model of a cyclic summand**: since `‖π(f)ξ‖ = ‖f‖_{L²(μ_ξ)}` with no
cyclicity hypothesis, `f ↦ π(f)ξ` extends to a unitary from `L²(μ_ξ)` onto the cyclic
subspace of `ξ`. -/
def repCyclicUnitary : Lp ℂ 2 (repMeasure pi xi) ≃ₗᵢ[ℂ] repCyclicSubspace pi xi :=
  (LinearEquiv.refl ℂ C(X, ℂ)).extendOfIsometry
    (ContinuousMap.toLp 2 (repMeasure pi xi) ℂ).toLinearMap
    (repVecTo pi xi)
    (ContinuousMap.toLp_denseRange ℂ _ (μ := repMeasure pi xi) (by simp))
    (denseRange_repVecTo pi xi)
    (fun f => by simpa using (norm_rep_apply pi xi f))

@[simp] theorem repCyclicUnitary_toLp (f : C(X, ℂ)) :
    repCyclicUnitary pi xi (ContinuousMap.toLp 2 (repMeasure pi xi) ℂ f) = repVecTo pi xi f :=
  LinearEquiv.extendOfIsometry_eq _ _ _ _ _ _ f

/-- The model read inside the ambient space: an isometric embedding of `L²(μ_ξ)` into
`H` with range the cyclic subspace of `ξ`. -/
def repEmbedding : Lp ℂ 2 (repMeasure pi xi) →ₗᵢ[ℂ] H :=
  (repCyclicSubspace pi xi).subtypeₗᵢ.comp (repCyclicUnitary pi xi).toLinearIsometry

@[simp] theorem repEmbedding_apply (u : Lp ℂ 2 (repMeasure pi xi)) :
    repEmbedding pi xi u = (repCyclicUnitary pi xi u : H) := rfl

@[simp] theorem repEmbedding_toLp (f : C(X, ℂ)) :
    repEmbedding pi xi (ContinuousMap.toLp 2 (repMeasure pi xi) ℂ f) = pi f xi := by
  simp [repEmbedding]







/-! ## 6. Gluing the summand models -/

variable {pi}





variable (pi)



/-! ## 7. The separable case -/

variable {pi}







variable (pi)



end BookProof.ChapterAbelianDirectSum

/-! ## 8. The Gelfand form -/

namespace BookProof.ChapterAbelianDirectSum

open BookProof.ChapterAbelianGelfandModel BookProof.ChapterAbelianCyclicModel

variable {A : Type*} [CommCStarAlgebra A]
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]



end BookProof.ChapterAbelianDirectSum

end
