import Definitions.Def_ChapterFiniteSectionSingleTime
import Definitions.Def_ChapterFockSecondQuantization
import Definitions.Def_ChapterQgCouplingDGammaSum
import Definitions.Def_ChapterSirkTrotterKato
import Definitions.Def_ChapterEsaClosureCore
import Definitions.Def_ChapterFarisLavine
import Definitions.Def_ChapterComplexShiftCore
import Definitions.Def_ChapterHermiteGalerkinFriedrichs
import Definitions.Def_ChapterHermiteProductCore
import Definitions.Def_ChapterNavierStokesAffineFiberEsa
import Definitions.Def_ChapterQgTimeIndependentFlow
import Definitions.Def_ChapterSirkSingleTimeShift
import Definitions.Def_ChapterStoneBridge
import Definitions.Def_ChapterYangMillsFriedrichs
import Definitions.Def_ChapterYangMillsHermite
import Mathlib

namespace BookProof.QymTimeIndependent

end BookProof.QymTimeIndependent
