import Definitions.Def_ChapterQgContinuumModeInstance
import Mathlib


/-!
# BRST derivative gauge fixing for the outer-Fock quantum-gravity Hamiltonian

The gauge fixing used throughout this project for Navier–Stokes
(`BookProof.ChapterNavierStokesGaugeY`) introduces an **auxiliary variable that the gauge
condition fixes to a spatial derivative of a field**: the modes `u_{i,j}` are constrained to
be the `y`-derivatives of `u_i(y)`, and the constraint is generated by a first-class
(abelian) generator, so it can be treated by BRST.  This module carries the same device over
to the quantum-gravity Hamiltonian of `BookProof.ChapterQgContinuumModeInstance`.

The extended (pre-gauge-fixed) variables are the vielbein modes `e_ν^i(k)` **together with**
auxiliary derivative modes `D_{μν}^i(k)`, one for every spatial derivative of every vielbein
component (`EMode`).  In these variables the torsion is *linear in the auxiliary variables
alone*,

`T_{μν}^i = D_{μν}^i − D_{νμ}^i`  (`extTorsionCoef`),

with no derivative appearing anywhere; the whole derivative content sits in the gauge
condition

`D_{μν}^i(k) = i k_μ e_ν^i(k)`,

which is exactly "an auxiliary variable is fixed to the spatial derivative of a field".
`gaugeReduce` performs the substitution on linear forms, and the two main identities are

* **`gaugeReduce_extTorsionCoef`** — the gauge-fixed extended torsion form is *exactly* the
  physical torsion form `k_μ e_ν^i − k_ν e_μ^i` of the continuum model;
* **`gaugeReduce_gram`** — hence the gauge-fixed Gram matrix of all extended torsion terms
  is exactly the vielbein self-interaction `contTorsionGram` of the continuum model.

Consequently the gauge-fixed quantum-gravity Hamiltonian is the continuum Hamiltonian, and
it is essentially self-adjoint on the outer Fock space
(**`brstGaugeFixed_esa`**, **`starobinsky_brstGaugeFixed_esa`**).

A second, independent ingredient is the general **restriction principle**
(`restrictModes`): admissible mode data restricted to *any* subset of modes — for
instance the physical modes surviving a gauge condition — is again admissible, so the
Faris–Lavine essential self-adjointness survives gauge fixing
(`restrict_essentiallySelfAdjointOn`).

Everything is `sorry`-free and `axiom`-free.
-/

namespace BookProof.QgBrstDerivativeGauge

open BookProof.ScalaronFiberFL BookProof.ScalaronOuterFockFL
open BookProof.QgVielbeinModeInstance BookProof.QgContinuumModeInstance
open BookProof.FarisLavine BookProof.QgOuterFockCoreFL

noncomputable section

/-! ## 1. The restriction principle: gauge fixing removes modes -/

open Classical in
/-- **Admissible mode data restricted to a subset of the modes.**  Every Faris–Lavine bound
survives, with the same constant `K`, because all the sums are sums of non-negative terms
over a smaller index set.  Gauge fixing — the passage to the modes that survive a gauge
condition — is an instance. -/
def restrictModes {ι : Type*} (Q : QgModeData ι) (s : Set ι) : QgModeData s where
  sig a := Q.sig a
  one_le_sig a := Q.one_le_sig a
  A a b := Q.A a b
  B a b := Q.B a b
  nbr a := (Q.nbr (a : ι)).subtype (· ∈ s)
  mem_nbr_comm a b := by
    simp only [Finset.mem_subtype]
    exact Q.mem_nbr_comm (a : ι) (b : ι)
  A_off a b hb := Q.A_off (a : ι) (b : ι) (fun hmem => hb (Finset.mem_subtype.mpr hmem))
  B_off a b hb := Q.B_off (a : ι) (b : ι) (fun hmem => hb (Finset.mem_subtype.mpr hmem))
  A_herm a b := Q.A_herm (a : ι) (b : ι)
  B_herm a b := Q.B_herm (a : ι) (b : ι)
  K := Q.K
  K_nonneg := Q.K_nonneg
  A_rel_row a := by
    refine le_trans ?_ (Q.A_rel_row (a : ι))
    rw [Finset.sum_subtype_eq_sum_filter (fun b => ‖Q.A (a : ι) b‖ / Q.sig b)]
    exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
      (fun b _ _ => div_nonneg (norm_nonneg _) (Q.sig_nonneg b))
  A_rel_col a := by
    refine le_trans ?_ (Q.A_rel_col (a : ι))
    rw [Finset.sum_subtype_eq_sum_filter (fun b => ‖Q.A (a : ι) b‖)]
    exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
      (fun b _ _ => norm_nonneg _)
  A_comm a := by
    refine le_trans ?_ (Q.A_comm (a : ι))
    rw [Finset.sum_subtype_eq_sum_filter (fun b => |Q.sig (a : ι) - Q.sig b| * ‖Q.A (a : ι) b‖)]
    exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
      (fun b _ _ => mul_nonneg (abs_nonneg _) (norm_nonneg _))
  B_rel a := by
    refine le_trans ?_ (Q.B_rel (a : ι))
    rw [Finset.sum_subtype_eq_sum_filter (fun b => ‖Q.B (a : ι) b‖)]
    exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
      (fun b _ _ => norm_nonneg _)
  B_comm a := by
    refine le_trans ?_ (Q.B_comm (a : ι))
    rw [Finset.sum_subtype_eq_sum_filter (fun b => |Q.sig (a : ι) - Q.sig b| * ‖Q.B (a : ι) b‖)]
    exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
      (fun b _ _ => mul_nonneg (abs_nonneg _) (norm_nonneg _))



/-! ## 2. The extended variables and the derivative gauge condition -/

/-- An auxiliary derivative mode `D_{μν}^i(k)`: a momentum together with the derivative
index `μ` and the vielbein indices `(ν, i)`. -/
abbrev DMode := Mom × Fin 3 × Fin 3 × Fin 3

/-- The extended (pre-gauge-fixed) modes: the vielbein modes together with the auxiliary
derivative modes. -/
abbrev EMode := CMode ⊕ DMode

/-- The momentum carried by an extended mode. -/
def emom : EMode → Mom
  | Sum.inl x => x.1
  | Sum.inr d => d.1

/-- **The torsion in the extended variables**: `T_{μν}^i = D_{μν}^i − D_{νμ}^i`, a linear
form in the *auxiliary* variables alone — no derivative appears. -/
def extTorsionCoef (k : Mom) (mu nu i : Fin 3) : EMode → ℂ
  | Sum.inl _ => 0
  | Sum.inr d =>
      if d.1 = k then
        ((if d.2 = (mu, nu, i) then 1 else 0) - (if d.2 = (nu, mu, i) then 1 else 0))
      else 0

/-- **The BRST derivative gauge condition, as a substitution on linear forms**: the
auxiliary variable `D_{μν}^i(k)` is replaced by the spatial derivative `k_μ e_ν^i(k)` of the
vielbein field.  (The factor `i` of the derivative symbol is a phase; it is omitted here
exactly as in the physical torsion form, and cancels in the Gram matrix.) -/
def gaugeReduce (F : EMode → ℂ) (x : CMode) : ℂ :=
  F (Sum.inl x) + ∑ rho : Fin 3, ((x.1 rho : ℤ) : ℂ) * F (Sum.inr (x.1, rho, x.2.1, x.2.2))









/-! ## 3. Essential self-adjointness of the gauge-fixed Hamiltonian -/







/-! ## 4. Non-vacuity of the extended description -/



end

end BookProof.QgBrstDerivativeGauge
