import Definitions.Def_ChapterQg3DGaugeEsa
import Definitions.Def_ChapterFarisLavineOnly
import Mathlib


/-!
# The 3D gauge-fixed gravity Hamiltonian in the jet coordinates, **through Faris–Lavine**

`BookProof.ChapterQg3DGaugeEsa` proves essential self-adjointness of the `84`-coordinate
3D gauge-fixed gravity Hamiltonian — the densitized, Weyl-ordered Hamiltonian whose
coordinates are the four spacetime coordinates, the sixteen tetrad components `e_μ^a` and
the sixty-four **independent coordinates `E_{μν}^a` representing the spatial derivatives of
the tetrad** — by the Carleman flux criterion.  That criterion does not lift to the outer
Fock space.  This module re-proves the same statement, and strengthens it, using **only**
the commutator criterion of Faris–Lavine with the Friedrichs extension of
`N₁ = −Δ + ‖x‖²/4` as comparison operator, which does lift.

## What is proved

* `qgSigned_eq_sqSumOp` — the identification: for every real signature `κ` the operator
  `½ Σ_j κ_j π_j² + ½ Σ_m T_m²` is the kinetic-plus-squares operator `sqSumOp κ torsionVec`.
* **`qgSigned_esa_fl`**, **`qg3D_esa_fl`** — essential self-adjointness on the
  Gauss–polynomial core of `L²(ℝ⁸⁴)`, by Faris–Lavine, for every real signature and in
  particular for the physical hyperbolic signature `qgKappa`.
* `div3Vec`, `timeDerivVec`, `qgGaugeVec` — the two gauge-fixing families, written as linear
  forms in the `84` coordinates: the **3D gauge condition** `Σ_j E_{jj}^a = 0` (the spatial
  divergence of the tetrad, expressed in the coordinates that represent its spatial
  derivatives) and the **gauge fixing of the derivative coordinates** `E_{0ν}^a = 0` (the
  coordinates representing time derivatives are fixed to zero, which is what makes the
  formulation three-dimensional).
* **`qg3DGaugeFixed_esa_fl`** — the gauge-fixed Hamiltonian, torsion *and* both gauge-fixing
  families together, is essentially self-adjoint on the core, by Faris–Lavine.
* **`qgGaugeOuterHam`, `qgGauge_sector_esa_fl`, `qgGauge_outerHam_esa_fl`** — the same
  Hamiltonian on the nested Fock space `⊕ₙ L²(ℝ^{84n})`, one copy of the one-particle
  Hamiltonian per particle, essentially self-adjoint on the finite-particle core.
* **`qg3DGaugeFixed_stone_flow`, `qgGauge_stone_flow`** — the unitary time evolution
  generated by the unique self-adjoint realization, on the one-particle space and on the
  nested Fock space (Stone).
* **`dsOp_number_conserving`, `qgGauge_number_conserving`** — the outer Hamiltonian
  **conserves the particle number**: it is block diagonal in the particle-number sectors, and
  its restriction to the `n`-particle sector is the `n`-particle Hamiltonian
  (`qgGaugeOuterHam_sector`).  This is what makes a spatial lattice regularization
  unnecessary: the sectors, not a lattice, cut the problem into pieces.

## Scope — this model carries **no scalaron**

The identification `qgSigned_eq_sqSumOp` of the Hamiltonian as a *kinetic-plus-squares*
operator is a statement about the pure tetrad/jet sector: kinetic term plus squares of
**linear** forms in the `84` coordinates.  It does **not** extend to the gravity Hamiltonian
this development delivers, which also carries the scalaron with the **full exponential**
Einstein-frame potential and no Taylor expansion: that potential is not a polynomial of
degree `≤ 2`, hence not a half-sum of squares of linear forms
(`BookProof.ScalaronNotQuadratic.starobinskyV_not_quadratic`,
`starobinskyPot_not_sum_of_squares`), so no kinetic-plus-squares identification of it is
possible or claimed.  The Hamiltonian with the vielbein, the scalaron, the 3D gauge fixing
and the gauge fixing of the derivative variables is
`BookProof.QgVielbeinScalaronGaugeFL.secHam _ (qgFullModes g)`, whose essential
self-adjointness on the outer Fock space is proved by Faris–Lavine against a comparison
operator whose fibre carries the exponential wall itself.

No spectral information and no mass gap is claimed.

Everything is `sorry`-free and `axiom`-free.
-/

namespace BookProof.Qg3DGaugeFL

open BookProof.QuantumGravity3DGauge BookProof.Qg3DGaugeEsa
open BookProof.QgOuterFock BookProof.FarisLavineOnly
open BookProof.HermiteProductCore BookProof.FarisLavine BookProof.DirectSumEsa
open BookProof.YangMillsHermite
open BookProof.StoneBridge BookProof.EsaClosure BookProof.ChapterStoneResolvent

noncomputable section

/-! ## 1. The one-particle Hamiltonian as a kinetic-plus-squares operator -/











/-! ## 2. The gauge-fixing forms -/

/-- The spatial directions among the four spacetime directions. -/
def spatial (j : Fin 3) : Fin 4 := j.succ

/-- **The 3D gauge condition** `Σ_j E_{jj}^a = 0`: the spatial divergence of the tetrad,
written in the coordinates that represent its spatial derivatives. -/
def div3Vec (a : Fin 4) (i : Fin 84) : ℝ :=
  ∑ j : Fin 3, (if i = idxDE (spatial j) (spatial j) a then 1 else 0)

/-- **The gauge fixing of the derivative coordinates** `E_{0ν}^a = 0`: the coordinates that
represent time derivatives of the tetrad are fixed to zero, which is what makes the
formulation three-dimensional. -/
def timeDerivVec (q : Fin 4 × Fin 4) (i : Fin 84) : ℝ :=
  if i = idxDE 0 q.1 q.2 then 1 else 0

/-- The complete gauge-fixing family: the four 3D gauge conditions and the sixteen
conditions on the derivative coordinates. -/
def qgGaugeVec : (Fin 4) ⊕ (Fin 4 × Fin 4) → Fin 84 → ℝ := Sum.elim div3Vec timeDerivVec

/-- The linear forms of the gauge-fixed Hamiltonian: the torsion forms together with the two
gauge-fixing families. -/
def qgFullVec : (Fin 64) ⊕ ((Fin 4) ⊕ (Fin 4 × Fin 4)) → Fin 84 → ℝ :=
  Sum.elim torsionVec qgGaugeVec











/-- **The complete 3D gauge-fixed gravity Hamiltonian on the one-particle space**:
`½ Σ_j κ_j π_j² + ½ Σ_m T_m² + ½ Σ (gauge-fixing forms)²`, with the independent coordinates
for the spatial derivatives of the tetrad, the 3D gauge condition and the gauge fixing of
the derivative coordinates. -/
def qg3DGaugeFixedHam : (polyGaussCore (d := 84)) →ₗ[ℂ] L2d 84 := sqSumOp qgKappa qgFullVec



/-! ## 3. The nested Fock space -/

/-- The `n`-particle lift of a one-particle family of linear forms: one copy of every form
in every particle's coordinate block. -/
def liftVecN {R : Type} [Fintype R] (v : R → Fin 84 → ℝ) (n : ℕ) (r : Fin n × R)
    (I : Fin (n * 84)) : ℝ :=
  if partOf I = r.1 then v r.2 (modeOf I) else 0

/-- **The `n`-particle gauge-fixed gravity Hamiltonian** `Σ_p h^{(p)}` on the
Gauss–polynomial core of `L²(ℝ^{84n})`. -/
def qgGaugeSectorHam (n : ℕ) : (polyGaussCore (d := n * 84)) →ₗ[ℂ] L2d (n * 84) :=
  sqSumOp (qgKappaN n) (liftVecN qgFullVec n)

/-- **The gauge-fixed gravity Hamiltonian on the nested Fock space.** -/
def qgGaugeOuterHam : qgOuterCore →ₗ[ℂ] qgOuterFock := dsOp (fun n : ℕ => qgGaugeSectorHam n)













/-! ## 4. Particle-number conservation -/

section Number

variable {ι : Type*} {G : ι → Type*} [∀ i, NormedAddCommGroup (G i)]
  [∀ i, InnerProductSpace ℂ (G i)] {D : ∀ i, Submodule ℂ (G i)}





end Number





end

end BookProof.Qg3DGaugeFL
