import Definitions.Def_ChapterBookBrstYangMills
import Mathlib


/-!
# The gauge-fixing fermion of `book.tex` and the gauge-fixing term it generates

`book.tex`, §*"Pure SU(3) Yang-Mills theory"* (line ~7347), adds to the Hamiltonian the
BRST-exact term generated by the **gauge-fixing fermion** `Ψ = i ψ_a A_{0a}`,

```
{Ω, i ψ_a A_{0a}} ,
```

and uses it to pass from the four-dimensional Hamiltonian to the Weyl-gauge Hamiltonian.
This module builds that construction for the BRST charge of
`BookProof.ChapterBookBrstYangMills`.

## What is proved

* `brstCharge_gf_anticomm` — the anticommutator of the abstract BRST charge
  `Ω = Σ_a 𝒢_a χ_a − ½ Σ f_{abe} χ_a χ_b β_e` with a **gauge-fixing fermion**
  `Ψ = Σ_d β_d B_d` built from bosonic operators `B_d`:

  ```
  {Ω, Ψ} = Σ_c 𝒢_c B_c − Σ_{c,d} [𝒢_c, B_d] β_d χ_c − Σ_{a,b,c} f_{abc} B_a χ_b β_c .
  ```

  The first term is the Gauss law contracted with the gauge-fixing field — in the book's
  application the term that cancels `π^μ_a (D_μ A_0)_a` in the Hamiltonian — the second is
  the ghost kinetic term and the third the non-abelian ghost–field coupling.
* `bookGfTerm_eq` — the same identity for the book's charge and the book's gauge-fixing
  fermion `Ψ = i ψ_a A_{0a}` on the graded state space, with `[𝒢_c, A_{0d}]` evaluated as
  multiplication by the gauge variation of the coordinate `A_{0d}`.
* `bookGfTerm_brst_closed` — the generated term is BRST invariant, `Ω {Ω,Ψ} = {Ω,Ψ} Ω`,
  because `Ω² = 0`; this is why the book may add it to the Hamiltonian without changing the
  BRST cohomology.
* **Accounting identity (temporal/Weyl gauge `A₀ = 0`)** —
  `bookGfFermion_eq_zero_of_Afield0` and `bookGfTerm_eq_zero_of_Afield0`: when every
  temporal component vanishes, `Ψ = i ψ_a A_{0a}` and hence `{Ω, Ψ}` are identically zero.
  The BRST-exact gauge-fixing/ghost contribution therefore adds **no new term** to the
  gauge-fixed Hamiltonian `h` and **no new summand** to the comparison operator `N`: the
  accounting of `h` and `N` is already complete without it.  For pure Yang–Mills (QYM) the
  same identity holds for the `su(2)`/`su(3)` instances — the Weyl gauge may work with the
  spatial components only.  For quantum gravity (QG) the book's 3D reduction is **not** the
  ADM one (`book.tex` ~8226–8244): it fixes the globally defined time-like vector
  `v^μ = δ^μ_0`, the ghosts of the resulting charge are **constant in the timepiece**, and
  the charge keeps the **same functional form as the 4D formalism** — explicitly different
  from the ADM BRST charge, whose approximation the book rejects as insufficient.

* `exactStates_le_physicalStates` — nilpotency makes the BRST cohomology
  `brstCohomology = ker Ω / im Ω` of the book's charge well defined, and
  `bookGfTerm_mem_physicalStates` / `bookGfTerm_mem_exactStates` show that the gauge-fixing
  term preserves both the physical and the exact states.  No claim is made about the
  dimension of the cohomology.

* `brstCharge_comm_of_comm` / `bookOmega_comm_multOp` — a **gauge-invariant observable**
  (one commuting with all the constraints and with the ghosts) commutes with the BRST charge,
  so it preserves the physical and the exact states; `casimir_bookOmega_comm` exhibits the
  quadratic invariant `Σ_{μ,a} A_{μa}A_{μa}` as such an observable for the constant
  gauge-field algebra.

Everything is `sorry`-free and `axiom`-free.
-/

namespace BookProof.BookBrstGaugeFixing

open MvPolynomial

noncomputable section

/-! ## 1. The abstract gauge-fixing anticommutator -/

section Abstract

variable {R : Type*} [Ring R] [Algebra ℝ R] {n : ℕ}
variable {f : Fin n → Fin n → Fin n → ℝ} {Gc χ β B : Fin n → R}

/-- The **gauge-fixing fermion** `Ψ = Σ_d ψ_d B_d` attached to a family of bosonic
operators `B_d` (the book's `Ψ = ψ_a A_{0a}`). -/
def gfFermion (β B : Fin n → R) : R := ∑ d, β d * B d









end Abstract

/-! ## 2. The book's gauge-fixing fermion `Ψ = i ψ_a A_{0a}` -/

variable {N : ℕ} (G : GaugeAlgebra N)

/-- **The gauge-fixing fermion of `book.tex`**, `Ψ = i ψ_a A_{0a}`. -/
def bookGfFermion : Module.End ℂ (BookState N) :=
  Complex.I • gfFermion betaOp (fun a => Afield 0 a)

-- Note: `bookGfFermion` does not depend on `G`; only `N` (and the operators) enter.

/-- **The gauge-fixing term** `{Ω, Ψ}` added to the Hamiltonian in `book.tex`. -/
def bookGfTerm : Module.End ℂ (BookState N) :=
  bookOmega G * bookGfFermion + bookGfFermion * bookOmega G





/-! ## 2b. The accounting identity: the gauge-fixing term vanishes at `A₀ = 0` -/







/-! ## 3. The BRST cohomology of the book's charge -/

/-- **Physical states**: the kernel of the book's BRST charge, `Ω |phys⟩ = 0`. -/
def physicalStates : Submodule ℂ (BookState N) := LinearMap.ker (bookOmega G)

/-- **BRST-exact states**: the image of the book's BRST charge. -/
def exactStates : Submodule ℂ (BookState N) := LinearMap.range (bookOmega G)



/-- The exact states, viewed inside the physical states. -/
def exactInPhysical : Submodule ℂ (physicalStates G) :=
  (exactStates G).comap (physicalStates G).subtype

/-- **The BRST cohomology of the charge of `book.tex`**: physical states modulo BRST-exact
states.  (No claim is made here about its dimension.) -/
abbrev brstCohomology := (physicalStates G) ⧸ exactInPhysical G





/-! ## 4. Gauge-invariant observables act on the BRST cohomology -/

section Observables

variable {R : Type*} [Ring R] [Algebra ℝ R] {n : ℕ}
variable {f : Fin n → Fin n → Fin n → ℝ} {Gc χ β : Fin n → R}







end Observables







/-! ## 5. A concrete gauge-invariant observable -/

/-- Multiplication by a polynomial in the gauge fields, as an operator on the graded state
space. -/
def multOp (p : FieldPoly N) : Module.End ℂ (BookState N) := bosOpN (LinearMap.mulLeft ℂ p)







/-- The quadratic invariant `Σ_{μ,a} A_{μa} A_{μa}` of the gauge fields. -/
def casimirPoly : FieldPoly N := ∑ i : Fin 4 × Fin N, X i * X i





end

end BookProof.BookBrstGaugeFixing
