import Definitions.Def_ChapterStoneGroup
import Mathlib


/-!
# The general Stone theorem, part III: the unitary group `e^{-itA}`

Using the Yosida approximations `A_n` of `BookProof.ChapterStoneGroup`, we form the
bounded unitary groups `e^{-itA_n}` and prepare the convergence estimate that produces
the unitary group generated by an unbounded self-adjoint `A`.
-/

open scoped InnerProductSpace
open Filter Topology NormedSpace

namespace BookProof.ChapterStoneResolvent

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The algebra of bounded operators is a `ℚ`-algebra; this is the instance under which
`NormedSpace.exp` is available. -/
noncomputable local instance ratNormedAlgebra : NormedAlgebra ℚ (H →L[ℂ] H) :=
  NormedAlgebra.restrictScalars ℚ ℂ (H →L[ℂ] H)



namespace UnboundedSelfAdjoint

variable (T : UnboundedSelfAdjoint H)

/-! ## The bounded approximating groups -/

/-- The skew-adjoint generator `-i A_n` of the approximating group. -/
noncomputable def yosidaGen (n : ℝ) : H →L[ℂ] H := (-Complex.I) • T.yosida n

/-- The approximating unitary group `e^{-i t A_n}`. -/
noncomputable def approxU (n t : ℝ) : H →L[ℂ] H := exp (t • T.yosidaGen n)























/-! ## The basic convergence estimate -/

 - 0‖ := hmvt
    _ = |t| * C := by rw [sub_zero, Real.norm_eq_abs]; ring

end UnboundedSelfAdjoint

end BookProof.ChapterStoneResolvent
