import Definitions.Def_ChapterQuantumGravityFock
import Definitions.Def_ChapterBrstReducedTransfer
import Mathlib


/-!
# The bounded BRST charge on the *completed* graded Hilbert space, and its reduced transfer

`CONSOLIDATED_PLAN.md` §10.6.2 item 4 is closed except for one join: the BRST charge of
`ChapterQuantumGravityBrstCharge` is built on the *algebraic* graded space
`ℂ[x₀,…,x₈₃] ⊗ Λ(ℂ¹⁹)`, whereas the reduced-transfer theorems of
`ChapterBrstReducedTransfer` need a **bounded** nilpotent charge on a *complete* space.
This module supplies exactly that missing object and performs the join.

## What is proved

* **A bounded weighted shift calculus on `ℓ²`** (`wshift`).  For a weight `w` with
  `‖w i‖ ≤ 1` and a reindexing `e` that is injective on the support of `w`, the map
  `f ↦ (i ↦ w i * f (e i))` is a bounded operator of norm `≤ 1` on `ℓ²(ι)`
  (`memlp_weighted`, `wshiftL_norm_le`).  This is the analytic content: the pullback of a
  square-summable family along a partially injective reindexing stays square-summable.
* **The ghost creation operators on the completed graded space.**  On
  `QGH = ℓ²(GradedIdx)` — the completion of the graded Fock space of
  `ChapterQuantumGravityFock`, `GradedIdx = BoseConf × FermConf` — the operator
  `brstTerm sym a` is `Ψ†_a` dressed with a bounded boson-sector constraint symbol
  `sym a : BoseConf → ℂ`.  It is bounded by `1` and satisfies the Jordan–Wigner
  anticommutation relations `brstTerm_comp_self` (`(Ψ†_a)² = 0`) and `brstTerm_anticomm`
  (`Ψ†_aΨ†_b + Ψ†_bΨ†_a = 0`).
* **The bounded nilpotent BRST charge** `qgBrstCharge sym = ∑_{a<19} sym_a Ψ†_a` over the
  book's `19` diffeomorphism ghosts: `qgBrstCharge_nilpotent` (`Ω² = 0`) and
  `qgBrstCharge_ne_zero` (it is not the zero operator, so the statement is not vacuous).
* **An explicit unitary group commuting with it**: `qgPhase omega t`, multiplication by
  `e^{-it·(boson energy)}`, with `qgPhase_zero`, `qgPhase_group`, `qgPhase_isometry` and
  `qgPhase_comm_brst`.  `qgPhase_single` identifies it on the occupation basis as the
  evolution generated by the graded Fock symbol `qgGradedSymbol omega 0` of
  `ChapterQuantumGravityFock` — the ghost-energy-free case, which is precisely the case in
  which the evolution commutes with the ghost ladder.
* **The join** (§10.6.2 item 4): `qgBrstTransfer` is the induced one-parameter group on the
  BRST cohomology `Cohomology (qgBrstCharge sym)` of the completed space, with
  `qgBrstTransfer_zero`, `qgBrstTransfer_comp`, `qgBrstTransfer_bijective`,
  `qgPhase_mem_physicalStates` (the §10.3 caveat: the evolution preserves the physical
  subspace) and `qgBrstTransfer_infDist` (the BRST quotient norm is preserved).

## Honest boundary

The charge is `Ω = ∑_a C_a Ψ†_a` with the constraint symbols `C_a` *diagonal* in the boson
occupation basis and bounded by one; the full gauge-fixed constraint algebra (whose
generators are unbounded) is not represented, and no claim is made that this `Ω` is the
BRST charge of the `R + αR²` theory.  What is claimed, and proved, is that the reduced
transfer of §10.6.2 item 4 now has a concrete bounded nilpotent charge on a complete
Hilbert space, together with a nontrivial commuting unitary group.  The Hamiltonian whose
group is used here has no ghost energy: a nonzero ghost energy does *not* commute with the
ghost ladder, so its evolution does not descend — that obstruction is recorded, not hidden.
-/

namespace BookProof.QgBrstCompleted

open scoped ENNReal
open BookProof BookProof.QuantumGravityFock BookProof.BrstReducedTransfer

noncomputable section

/-! ## A bounded weighted-shift calculus on `ℓ²` -/

section WeightedShift

variable {ι : Type*}

/-- `ℓ²` over an arbitrary index type. -/
abbrev L2 (ι : Type*) := lp (fun _ : ι => ℂ) 2

theorem le_of_rpow_two_le {a b : ℝ} (hb : 0 ≤ b) (h : a ^ (2 : ℝ) ≤ b ^ (2 : ℝ)) : a ≤ b := by
  rw [show (2 : ℝ) = ((2 : ℕ) : ℝ) by norm_num, Real.rpow_natCast, Real.rpow_natCast] at h
  nlinarith

theorem summable_sq_lp (f : L2 ι) : Summable fun j => ‖f j‖ ^ (2 : ℝ) := by
  have hp : (0 : ℝ) < ((2 : ℝ≥0∞)).toReal := by norm_num
  have h := lp.memℓp f
  rw [memℓp_gen_iff hp] at h
  simpa using h

/-- **The analytic heart.**  Pulling a square-summable family back along a reindexing that
is injective on the support of a weight bounded by one keeps it square-summable, and does
not increase the sum. -/
theorem tsum_sq_weighted_le (w : ι → ℂ) (e : ι → ι) (hw : ∀ i, ‖w i‖ ≤ 1)
    (hinj : Set.InjOn e {i | w i ≠ 0}) (f : ι → ℂ) (hf : Summable fun j => ‖f j‖ ^ (2 : ℝ)) :
    Summable (fun i => ‖w i * f (e i)‖ ^ (2 : ℝ)) ∧
      ∑' i, ‖w i * f (e i)‖ ^ (2 : ℝ) ≤ ∑' j, ‖f j‖ ^ (2 : ℝ) := by
  classical
  set S : Set ι := {i | w i ≠ 0} with hS
  have hinj' : Function.Injective (fun x : S => e (x : ι)) := fun x y hxy =>
    Subtype.ext (hinj x.2 y.2 hxy)
  have hsub : Summable (fun x : S => ‖f (e (x : ι))‖ ^ (2 : ℝ)) := hf.comp_injective hinj'
  have hind : Summable (S.indicator (fun i => ‖f (e i)‖ ^ (2 : ℝ))) :=
    summable_subtype_iff_indicator.mp hsub
  have hle : ∀ i, ‖w i * f (e i)‖ ^ (2 : ℝ) ≤ S.indicator (fun i => ‖f (e i)‖ ^ (2 : ℝ)) i := by
    intro i
    by_cases hi : i ∈ S
    · rw [Set.indicator_of_mem hi]
      have h1 : ‖w i * f (e i)‖ ≤ ‖f (e i)‖ := by
        rw [norm_mul]
        calc ‖w i‖ * ‖f (e i)‖ ≤ 1 * ‖f (e i)‖ :=
              mul_le_mul_of_nonneg_right (hw i) (norm_nonneg _)
          _ = ‖f (e i)‖ := one_mul _
      exact Real.rpow_le_rpow (norm_nonneg _) h1 (by norm_num)
    · have hw0 : w i = 0 := by simpa [hS] using hi
      simp [hw0, Set.indicator_of_notMem hi]
  have hsum : Summable (fun i => ‖w i * f (e i)‖ ^ (2 : ℝ)) :=
    hind.of_nonneg_of_le (fun i => by positivity) hle
  refine ⟨hsum, ?_⟩
  calc ∑' i, ‖w i * f (e i)‖ ^ (2 : ℝ) ≤ ∑' i, S.indicator (fun i => ‖f (e i)‖ ^ (2 : ℝ)) i :=
        hsum.tsum_le_tsum hle hind
    _ = ∑' x : S, ‖f (e (x : ι))‖ ^ (2 : ℝ) := (tsum_subtype S _).symm
    _ ≤ ∑' j, ‖f j‖ ^ (2 : ℝ) :=
        hsub.tsum_le_tsum_of_inj (fun x : S => e (x : ι)) hinj' (fun c _ => by positivity)
          (fun _ => le_refl _) hf

theorem memlp_weighted (w : ι → ℂ) (e : ι → ι) (hw : ∀ i, ‖w i‖ ≤ 1)
    (hinj : Set.InjOn e {i | w i ≠ 0}) (f : L2 ι) :
    Memℓp (fun i => w i * f (e i)) 2 := by
  have hp : (0 : ℝ) < ((2 : ℝ≥0∞)).toReal := by norm_num
  rw [memℓp_gen_iff hp]
  simpa using (tsum_sq_weighted_le w e hw hinj (fun i => f i) (summable_sq_lp f)).1

variable (w : ι → ℂ) (e : ι → ι) (hw : ∀ i, ‖w i‖ ≤ 1) (hinj : Set.InjOn e {i | w i ≠ 0})

include hw hinj in
/-- The weighted shift as a linear map on `ℓ²`. -/
def wshiftL : L2 ι →ₗ[ℂ] L2 ι where
  toFun f := ⟨fun i => w i * f (e i), memlp_weighted w e hw hinj f⟩
  map_add' f g := by ext i; simp only [lp.coeFn_add, Pi.add_apply, mul_add]
  map_smul' c f := by ext i; simp [mul_left_comm]



theorem wshiftL_norm_le (f : L2 ι) : ‖wshiftL w e hw hinj f‖ ≤ ‖f‖ := by
  have hp : (0 : ℝ) < ((2 : ℝ≥0∞)).toReal := by norm_num
  have h1 := lp.norm_rpow_eq_tsum hp (wshiftL w e hw hinj f)
  have h2 := lp.norm_rpow_eq_tsum hp f
  have hle := (tsum_sq_weighted_le w e hw hinj (fun i => f i) (summable_sq_lp f)).2
  rw [show ((2 : ℝ≥0∞)).toReal = 2 by norm_num] at h1 h2
  refine le_of_rpow_two_le (norm_nonneg f) ?_
  rw [h1, h2]
  simpa using hle

/-- **The bounded weighted shift** `f ↦ (i ↦ w i · f (e i))` on `ℓ²`, of norm at most one. -/
def wshift : L2 ι →L[ℂ] L2 ι :=
  LinearMap.mkContinuous (wshiftL w e hw hinj) 1 fun f => by
    simpa using wshiftL_norm_le w e hw hinj f







end WeightedShift

/-! ## The completed graded Hilbert space and the ghost creation operators -/

/-- The **completed** graded state space: the `ℓ²` completion of the graded Fock space of
`ChapterQuantumGravityFock`, indexed by joint boson/ghost occupations. -/
abbrev QGH := L2 GradedIdx

/-- The weight of the `a`-th dressed ghost creation operator: the Jordan–Wigner sign times a
bounded boson-sector constraint symbol, supported on the configurations occupying `a`. -/
def ghostWeight (sym : ℕ → BoseConf → ℂ) (a : ℕ) : GradedIdx → ℂ :=
  fun p => if a ∈ p.2 then sym a p.1 * jwSign a p.2 else 0

/-- The reindexing of the `a`-th ghost creation operator: remove the ghost `a`. -/
def ghostShift (a : ℕ) : GradedIdx → GradedIdx := fun p => (p.1, p.2.erase a)

theorem norm_jwSign (a : ℕ) (α : FermConf) : ‖jwSign a α‖ = 1 := by
  rw [jwSign, norm_pow, norm_neg, norm_one, one_pow]

theorem ghostWeight_norm_le {sym : ℕ → BoseConf → ℂ} (hsym : ∀ a n, ‖sym a n‖ ≤ 1) (a : ℕ)
    (p : GradedIdx) : ‖ghostWeight sym a p‖ ≤ 1 := by
  rw [ghostWeight]
  split
  · rw [norm_mul, norm_jwSign, mul_one]; exact hsym a p.1
  · simp

theorem ghostShift_injOn (sym : ℕ → BoseConf → ℂ) (a : ℕ) :
    Set.InjOn (ghostShift a) {p : GradedIdx | ghostWeight sym a p ≠ 0} := by
  intro p hp q hq hpq
  have hpa : a ∈ p.2 := by
    by_contra h
    exact hp (by simp [ghostWeight, h])
  have hqa : a ∈ q.2 := by
    by_contra h
    exact hq (by simp [ghostWeight, h])
  obtain ⟨h1, h2⟩ : p.1 = q.1 ∧ p.2.erase a = q.2.erase a := by
    simpa [ghostShift, Prod.ext_iff] using hpq
  have h3 : p.2 = q.2 := by
    rw [← Finset.insert_erase hpa, ← Finset.insert_erase hqa, h2]
  exact Prod.ext h1 h3

/-- **The dressed ghost creation operator** `C_a Ψ†_a` on the completed graded space: a
bounded operator of norm at most one. -/
def brstTerm (sym : ℕ → BoseConf → ℂ) (hsym : ∀ a n, ‖sym a n‖ ≤ 1) (a : ℕ) : QGH →L[ℂ] QGH :=
  wshift (ghostWeight sym a) (ghostShift a) (ghostWeight_norm_le hsym a) (ghostShift_injOn sym a)

@[simp] theorem brstTerm_apply {sym : ℕ → BoseConf → ℂ} (hsym : ∀ a n, ‖sym a n‖ ≤ 1) (a : ℕ)
    (f : QGH) (p : GradedIdx) :
    (brstTerm sym hsym a f) p =
      (if a ∈ p.2 then sym a p.1 * jwSign a p.2 else 0) * f (p.1, p.2.erase a) := rfl







/-! ## The bounded nilpotent BRST charge -/

/-- **The bounded BRST charge** on the completed graded space: the sum of the dressed ghost
creations over the book's `19` diffeomorphism ghosts. -/
def qgBrstCharge (sym : ℕ → BoseConf → ℂ) (hsym : ∀ a n, ‖sym a n‖ ≤ 1) : QGH →L[ℂ] QGH :=
  ∑ a ∈ Finset.range qgGhostModes, brstTerm sym hsym a

theorem qgBrstCharge_apply_eq_sum {sym : ℕ → BoseConf → ℂ} (hsym : ∀ a n, ‖sym a n‖ ≤ 1)
    (f : QGH) :
    qgBrstCharge sym hsym f = ∑ a ∈ Finset.range qgGhostModes, brstTerm sym hsym a f := by
  rw [qgBrstCharge, ContinuousLinearMap.sum_apply]





/-- The undressed (unit-symbol) BRST charge. -/
def oneSym : ℕ → BoseConf → ℂ := fun _ _ => 1







/-! ## An explicit unitary group commuting with the charge -/

/-- The phase weight `e^{-it·E(n)}` of the boson-diagonal evolution. -/
def phaseWeight (omega : ℕ → ℝ) (t : ℝ) : GradedIdx → ℂ :=
  fun p => Complex.exp (-(t * BookProof.NavierStokesFlow.FockOfFock.confEnergy omega p.1) *
    Complex.I)

theorem phaseWeight_norm (omega : ℕ → ℝ) (t : ℝ) (p : GradedIdx) :
    ‖phaseWeight omega t p‖ = 1 := by
  rw [phaseWeight, mul_comm]
  rw [Complex.norm_exp]
  simp

theorem phaseWeight_norm_le (omega : ℕ → ℝ) (t : ℝ) (p : GradedIdx) :
    ‖phaseWeight omega t p‖ ≤ 1 := le_of_eq (phaseWeight_norm omega t p)

theorem id_injOn (omega : ℕ → ℝ) (t : ℝ) :
    Set.InjOn (id : GradedIdx → GradedIdx) {p | phaseWeight omega t p ≠ 0} :=
  fun _ _ _ _ h => h

/-- **The evolution group** on the completed graded space: multiplication by the phase
`e^{-it·E(n)}` of the boson energy.  This is the unitary group generated by the graded Fock
Hamiltonian of `ChapterQuantumGravityFock` with vanishing ghost energy. -/
def qgPhase (omega : ℕ → ℝ) (t : ℝ) : QGH →L[ℂ] QGH :=
  wshift (phaseWeight omega t) id (phaseWeight_norm_le omega t) (id_injOn omega t)

@[simp] theorem qgPhase_apply (omega : ℕ → ℝ) (t : ℝ) (f : QGH) (p : GradedIdx) :
    (qgPhase omega t f) p = phaseWeight omega t p * f p := rfl









/-- The evolution commutes with the BRST charge: the phase depends only on the boson
occupation, which the ghost ladder does not change. -/
theorem qgPhase_comm_brst {sym : ℕ → BoseConf → ℂ} (hsym : ∀ a n, ‖sym a n‖ ≤ 1)
    (omega : ℕ → ℝ) (t : ℝ) (f : QGH) :
    qgPhase omega t (qgBrstCharge sym hsym f) = qgBrstCharge sym hsym (qgPhase omega t f) := by
  classical
  have hterm : ∀ a : ℕ, qgPhase omega t (brstTerm sym hsym a f)
      = brstTerm sym hsym a (qgPhase omega t f) := by
    intro a
    ext p
    rw [qgPhase_apply, brstTerm_apply, brstTerm_apply, qgPhase_apply]
    rw [phaseWeight, phaseWeight]
    ring
  rw [qgBrstCharge_apply_eq_sum, qgBrstCharge_apply_eq_sum, map_sum]
  exact Finset.sum_congr rfl fun a _ => hterm a

/-! ## The ghost-energy obstruction -/

/-- The phase weight of the **full** graded Fock symbol, boson energy *plus* ghost energy. -/
def fullPhaseWeight (omega g : ℕ → ℝ) (t : ℝ) : GradedIdx → ℂ :=
  fun p => Complex.exp (-(t * qgGradedSymbol omega g p) * Complex.I)

theorem fullPhaseWeight_norm (omega g : ℕ → ℝ) (t : ℝ) (p : GradedIdx) :
    ‖fullPhaseWeight omega g t p‖ = 1 := by
  rw [fullPhaseWeight, mul_comm, Complex.norm_exp]
  simp

theorem fullPhaseWeight_norm_le (omega g : ℕ → ℝ) (t : ℝ) (p : GradedIdx) :
    ‖fullPhaseWeight omega g t p‖ ≤ 1 := le_of_eq (fullPhaseWeight_norm omega g t p)

theorem id_injOn_full (omega g : ℕ → ℝ) (t : ℝ) :
    Set.InjOn (id : GradedIdx → GradedIdx) {p | fullPhaseWeight omega g t p ≠ 0} :=
  fun _ _ _ _ h => h

/-- The evolution generated by the **full** graded Fock symbol: boson energy plus ghost
energy.  It is again a unitary group on the completed graded space. -/
def qgPhaseFull (omega g : ℕ → ℝ) (t : ℝ) : QGH →L[ℂ] QGH :=
  wshift (fullPhaseWeight omega g t) id (fullPhaseWeight_norm_le omega g t)
    (id_injOn_full omega g t)







/-! ## The join: the BRST-reduced transfer on the completed graded space -/

variable {sym : ℕ → BoseConf → ℂ} (hsym : ∀ a n, ‖sym a n‖ ≤ 1) (omega : ℕ → ℝ)

include hsym in
/-- The commutation hypothesis in the exact shape the reduction theorems consume. -/
theorem qgPhase_commutes :
    ∀ (t : ℝ) (y : QGH), qgPhase omega t (qgBrstCharge sym hsym y)
      = qgBrstCharge sym hsym (qgPhase omega t y) :=
  fun t y => qgPhase_comm_brst hsym omega t y







/-- **The BRST-reduced transfer of §10.6.2 item 4**, now on the completed graded Hilbert
space with a genuinely bounded nilpotent charge. -/
def qgBrstTransfer (t : ℝ) :
    Cohomology (qgBrstCharge sym hsym) →ₗ[ℂ] Cohomology (qgBrstCharge sym hsym) :=
  transfer (qgBrstCharge sym hsym) (qgPhase omega) (qgPhase_commutes hsym omega) t









end

end BookProof.QgBrstCompleted
