import Definitions.Def_ChapterSpectralMultiplication
import Definitions.Def_ChapterLinftyMaximalAbelian
import Definitions.Def_ChapterAbelianGelfandModel
import Definitions.Def_ChapterLinftyMultiplication
import Mathlib


/-!
# The commutant of a singly generated abelian algebra (plan GAP-2, the von Neumann level)

`ChapterSpectralMultiplication` identifies a normal operator with a cyclic unit
vector with multiplication by the coordinate function on `L²(μ)`.  That is the
**C\*-level** model: it identifies the algebra of *continuous* functions of `T`.

This module upgrades the identification to the **von Neumann level** in the same
(cyclic) situation, by computing the *commutant*.  Two ingredients:

* a strengthening of `ChapterLinftyMaximalAbelian.commutant_eq_multOp`: on a compact
  space with a finite regular Borel measure it is enough to commute with the
  multiplication operators whose symbol is **continuous**
  (`contCommutant_eq_multOp`) — the essential bound on the symbol is obtained by
  truncating and testing against continuous functions, which are dense in `L²`;
* the transport of that statement through the spectral unitary
  (`commutant_eq_conj_multOp`).

The consequences are the von Neumann statements in the cyclic case:

* `centralizer_cfcSet` — the commutant of `{f(T) : f ∈ C(σ(T))}` is *exactly* the
  unitary copy of the multiplication algebra `L∞(μ)`;
* `centralizer_multModel` and `bicommutant_cfcSet` — that copy is its own
  commutant, so the **bicommutant** of `{f(T)}`, i.e. the von Neumann algebra
  generated by `T`, is again the unitary copy of `L∞(μ)`;
* `commutant_cfcSet_isCommutative` — in particular the commutant is abelian, i.e.
  the algebra generated by a normal operator with a cyclic vector is *maximal*
  abelian.

Everything is `sorry`-free and `axiom`-free.  What is still not claimed is the
non-cyclic case: a general separable Hilbert space decomposes into a direct sum of
cyclic subspaces, and assembling the models over that decomposition is not done
here.
-/

noncomputable section

open MeasureTheory ENNReal Complex

namespace BookProof.ChapterSpectralCommutant

open BookProof.ChapterLinftyMultiplication BookProof.ChapterLinftyMaximalAbelian
open BookProof.ChapterAbelianGelfandModel BookProof.ChapterSpectralMultiplication

/-! ## 1. The multiplication algebra and its commutant -/

section Algebra

variable {α : Type*} [MeasurableSpace α] {μ : Measure α}

/-- The **multiplication algebra** of `μ`: the bounded operators on `L²(μ)` that are
multiplication by an essentially bounded symbol. -/
def multAlgebra (μ : Measure α) : Set (Lp ℂ 2 μ →L[ℂ] Lp ℂ 2 μ) :=
  {S | ∃ (ψ : α → ℂ) (hψ : MemLp ψ ⊤ μ), S = multOp ψ hψ}









end Algebra

/-! ## 2. Continuous symbols suffice -/

section ContinuousSymbols

variable {X : Type*} [TopologicalSpace X] [CompactSpace X] [T2Space X]
  [MeasurableSpace X] [BorelSpace X] {mu : Measure X} [IsFiniteMeasure mu] [mu.WeaklyRegular]

/-- Commuting with every multiplication operator whose symbol is **continuous**. -/
def CommutesWithContMult (S : Lp ℂ 2 mu →L[ℂ] Lp ℂ 2 mu) : Prop :=
  ∀ g : C(X, ℂ), S.comp (mulRep mu g) = (mulRep mu g).comp S

















end ContinuousSymbols

/-! ## 3. Transport through the spectral unitary -/

section Operator

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (T : H →L[ℂ] H) (hT : IsStarNormal T) (xi : H)
  (hcyc : DenseRange (cfcVec T hT xi))

/-- Conjugation of an operator on `L²(μ)` by the spectral unitary. -/
def conjSpectral (S : Lp ℂ 2 (spectralMeasure T hT xi) →L[ℂ] Lp ℂ 2 (spectralMeasure T hT xi)) :
    H →L[ℂ] H :=
  ((spectralUnitary T hT xi hcyc).toLinearIsometry.toContinuousLinearMap).comp
    (S.comp ((spectralUnitary T hT xi hcyc).symm.toLinearIsometry.toContinuousLinearMap))

@[simp] theorem conjSpectral_apply
    (S : Lp ℂ 2 (spectralMeasure T hT xi) →L[ℂ] Lp ℂ 2 (spectralMeasure T hT xi)) (v : H) :
    conjSpectral T hT xi hcyc S v
      = spectralUnitary T hT xi hcyc (S ((spectralUnitary T hT xi hcyc).symm v)) := rfl

/-- Conjugation of an operator on `H` back to `L²(μ)`. -/
def conjSpectralSymm (S : H →L[ℂ] H) :
    Lp ℂ 2 (spectralMeasure T hT xi) →L[ℂ] Lp ℂ 2 (spectralMeasure T hT xi) :=
  ((spectralUnitary T hT xi hcyc).symm.toLinearIsometry.toContinuousLinearMap).comp
    (S.comp ((spectralUnitary T hT xi hcyc).toLinearIsometry.toContinuousLinearMap))

@[simp] theorem conjSpectralSymm_apply (S : H →L[ℂ] H)
    (u : Lp ℂ 2 (spectralMeasure T hT xi)) :
    conjSpectralSymm T hT xi hcyc S u
      = (spectralUnitary T hT xi hcyc).symm (S (spectralUnitary T hT xi hcyc u)) := rfl







/-- The continuous functional calculus algebra of `T`. -/
def cfcSet : Set (H →L[ℂ] H) := Set.range fun g : C(spectrum ℂ T, ℂ) => cfcHom hT g

/-- The unitary copy of the multiplication algebra `L∞(μ)` inside `B(H)`. -/
def multModel : Set (H →L[ℂ] H) :=
  conjSpectral T hT xi hcyc '' multAlgebra (spectralMeasure T hT xi)















end Operator

end BookProof.ChapterSpectralCommutant

end
