import Theorems.Thm_BookProof_ChapterDutchBook_Coherent_univ

import Definitions.Def_ChapterPvmMeasure
import Mathlib


/-!
# Decomposition of a projection-valued measure into cyclic pieces

`BookProof.ChapterPvmCyclicUnitary` and `BookProof.ChapterMackeyConverse` prove the
converse of Mackey's imprimitivity theorem over a continuous base **in the cyclic case**,
and record the honest boundary that the general case is obtained from it "by decomposing
the Hilbert space into cyclic subspaces, which is not formalized here".  This file
formalizes that decomposition.

## Results

* `OrthOrbit P ψ φ` — the cyclic subspaces generated by `ψ` and `φ` are orthogonal, in the
  convenient one-set form `⟪ψ, P(E) φ⟫ = 0`; `orthOrbit_pairs` shows that it implies the
  orthogonality `⟪P(E) ψ, P(F) φ⟫ = 0` of all the generators, and `OrthOrbit.symm` that it
  is a symmetric relation.
* **`exists_orthCyclicFamily`** — every projection-valued measure on a complete complex
  inner-product space admits a family `S` of unit vectors that are pairwise
  cyclic-orthogonal and **total**: the span of the union of their orbits `P(E) ψ` is dense.
  Such a family is orthonormal (`orthonormal_of_orthCyclicFamily`).  The proof is Zorn's
  lemma: maximality of `S` is contradicted by any unit vector of the orthogonal complement
  of the span, which generates a cyclic subspace orthogonal to all the others.
* `Pvm.restrictSub` — the restriction of a projection-valued measure to a closed invariant
  subspace is a projection-valued measure on that subspace; `cyclicSubspace P ψ` is such a
  subspace and `isCyclic_restrictCyclic` says that on it the restricted projection-valued
  measure has `ψ` as a **cyclic vector**.
* **`exists_cyclic_decomposition`** — the two together: the Hilbert space is the closed
  span of mutually orthogonal cyclic subspaces, on each of which the restricted
  projection-valued measure is cyclic.  Feeding each piece to
  `BookProof.ChapterPvmCyclicUnitary.pvm_cyclic_unitary` exhibits every projection-valued
  measure as an orthogonal sum of multiplication measures on `L²` spaces.

The assembly of those pieces into a *single* system — one unitary onto the `ℓ²`-sum of the
fibres, and, in the homogeneous case, onto `L²(X, μ; K)` with a multiplicity (fibre) Hilbert
space `K` — is carried out in `BookProof.ChapterPvmInducedSystem`,
`BookProof.ChapterL2FibreSum` and `BookProof.ChapterPvmFibreInducedSystem`.

Everything is `sorry`-free and uses only the standard axioms.
-/

open MeasureTheory
open scoped InnerProductSpace

namespace BookProof.ChapterPvmCyclicDecomposition

open BookProof.ChapterPvmMeasure

variable {X : Type*} [MeasurableSpace X]
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]

/-! ## Orthogonality of two cyclic subspaces -/

/-- The cyclic subspaces generated by `ψ` and `φ` are orthogonal.  Only one set is needed:
the generators are `P(E) ψ` and `P(F) φ`, and `⟪P(E) ψ, P(F) φ⟫ = ⟪ψ, P(E ∩ F) φ⟫`. -/
def OrthOrbit (P : Pvm X H) (ψ φ : H) : Prop :=
  ∀ E : Set X, MeasurableSet E → ⟪ψ, P.p E φ⟫_ℂ = 0



theorem OrthOrbit.symm {P : Pvm X H} {ψ φ : H} (h : OrthOrbit P ψ φ) : OrthOrbit P φ ψ := by
  intro E hE
  have h1 : ⟪P.p E ψ, φ⟫_ℂ = ⟪ψ, P.p E φ⟫_ℂ := P.symm hE _ _
  have h2 : ⟪P.p E ψ, φ⟫_ℂ = 0 := by rw [h1]; exact h E hE
  have h3 := congrArg (starRingEnd ℂ) h2
  rwa [inner_conj_symm, map_zero] at h3



/-! ## Families with pairwise orthogonal cyclic subspaces -/

/-- The union of the orbits of a family of vectors. -/
def familyOrbit (P : Pvm X H) (S : Set H) : Set H := ⋃ ψ ∈ S, pvmOrbit P ψ





/-- A family of unit vectors with pairwise orthogonal cyclic subspaces. -/
structure OrthCyclicFamily (P : Pvm X H) (S : Set H) : Prop where
  /-- every member is a unit vector -/
  unit : ∀ ψ ∈ S, ‖ψ‖ = 1
  /-- distinct members generate orthogonal cyclic subspaces -/
  orth : ∀ ψ ∈ S, ∀ φ ∈ S, ψ ≠ φ → OrthOrbit P ψ φ



/-! ## Zorn's lemma: a maximal family is total -/



/-! ## Restriction to a closed invariant subspace -/

/-- The cyclic subspace generated by `ψ`: the closure of the span of its orbit. -/
noncomputable def cyclicSubspace (P : Pvm X H) (ψ : H) : Submodule ℂ H :=
  (Submodule.span ℂ (pvmOrbit P ψ)).topologicalClosure



theorem cyclicSubspace_invariant (P : Pvm X H) (ψ : H) {E : Set X} (hE : MeasurableSet E)
    {v : H} (hv : v ∈ cyclicSubspace P ψ) : P.p E v ∈ cyclicSubspace P ψ := by
  set T : Submodule ℂ H := cyclicSubspace P ψ with hT
  have hclosed : IsClosed ((Submodule.comap (P.p E : H →ₗ[ℂ] H) T : Submodule ℂ H) : Set H) := by
    have : ((Submodule.comap (P.p E : H →ₗ[ℂ] H) T : Submodule ℂ H) : Set H)
        = (P.p E) ⁻¹' (T : Set H) := rfl
    rw [this]
    exact (Submodule.isClosed_topologicalClosure _).preimage (P.p E).continuous
  have hsub : Submodule.span ℂ (pvmOrbit P ψ) ≤ Submodule.comap (P.p E : H →ₗ[ℂ] H) T := by
    rw [Submodule.span_le]
    rintro _ ⟨F, hF, rfl⟩
    have : P.p E (P.p F ψ) = P.p (E ∩ F) ψ := P.inter hE hF _
    change P.p E (P.p F ψ) ∈ T
    rw [this]
    exact Submodule.le_topologicalClosure _ (Submodule.subset_span ⟨E ∩ F, hE.inter hF, rfl⟩)
  exact (Submodule.topologicalClosure_minimal _ hsub hclosed) hv

/-- A series converges in a subspace as soon as the series of the ambient vectors does. -/
theorem hasSum_subtype {V : Submodule ℂ H} {g : ℕ → V} {a : V}
    (h : HasSum (fun i => (g i : H)) (a : H)) : HasSum g a := by
  rw [HasSum, tendsto_subtype_rng]
  simpa using! h

open Classical in
/-- The projection of the restricted measure: the restriction of `P(E)` to an invariant
subspace (and `0` on non-measurable sets, which the axioms never mention). -/
noncomputable def restrictMap (P : Pvm X H) (V : Submodule ℂ H)
    (hV : ∀ E : Set X, MeasurableSet E → ∀ v ∈ V, P.p E v ∈ V) (E : Set X) : V →L[ℂ] V :=
  if h : MeasurableSet E then
    ContinuousLinearMap.codRestrict ((P.p E).comp V.subtypeL) V (fun v => hV E h v v.2)
  else 0

theorem restrictMap_apply {P : Pvm X H} {V : Submodule ℂ H}
    {hV : ∀ E : Set X, MeasurableSet E → ∀ v ∈ V, P.p E v ∈ V} {E : Set X}
    (hE : MeasurableSet E) (v : V) :
    ((restrictMap P V hV E v : V) : H) = P.p E (v : H) := by
  rw [restrictMap, dif_pos hE]
  rfl

/-- The restriction of a projection-valued measure to a closed invariant subspace. -/
noncomputable def restrictSub (P : Pvm X H) (V : Submodule ℂ H) [CompleteSpace V]
    (hV : ∀ E : Set X, MeasurableSet E → ∀ v ∈ V, P.p E v ∈ V) : Pvm X V where
  p := restrictMap P V hV
  symm := by
    intro E hE u v
    have hl : ⟪restrictMap P V hV E u, v⟫_ℂ = ⟪P.p E (u : H), (v : H)⟫_ℂ := by
      rw [← restrictMap_apply (hV := hV) hE u]; rfl
    have hr : ⟪u, restrictMap P V hV E v⟫_ℂ = ⟪(u : H), P.p E (v : H)⟫_ℂ := by
      rw [← restrictMap_apply (hV := hV) hE v]; rfl
    rw [hl, hr]
    exact P.symm hE (u : H) (v : H)
  inter := by
    intro E F hE hF u
    refine Subtype.ext ?_
    rw [restrictMap_apply hE, restrictMap_apply hF, restrictMap_apply (hE.inter hF)]
    exact P.inter hE hF (u : H)
  univ := by
    intro u
    refine Subtype.ext ?_
    rw [restrictMap_apply MeasurableSet.univ]
    exact P.univ (u : H)
  hasSum := by
    intro f hf hdisj u
    have hU : MeasurableSet (⋃ i, f i) := MeasurableSet.iUnion hf
    have hH := P.hasSum f hf hdisj (u : H)
    refine hasSum_subtype ?_
    rw [restrictMap_apply hU]
    exact hH.congr_fun (fun i => restrictMap_apply (hf i) u)



/-- The restriction of `P` to the cyclic subspace generated by `ψ`. -/
noncomputable def restrictCyclic [CompleteSpace H] (P : Pvm X H) (ψ : H) :
    Pvm X (cyclicSubspace P ψ) :=
  haveI : CompleteSpace (cyclicSubspace P ψ) :=
    (Submodule.isClosed_topologicalClosure _).completeSpace_coe
  restrictSub P (cyclicSubspace P ψ) (fun _ hE _ hv => cyclicSubspace_invariant P ψ hE hv)









/-! ## The decomposition -/



/-! ## Countability in a separable space -/





end BookProof.ChapterPvmCyclicDecomposition
