-- Generated from ChapterSmFockEsa.lean — theorem BookProof.SmFockEsa.smSecMomIdx_injective
import Definitions.Def_ChapterSmOneParticle
import Definitions.Def_ChapterSmOuterFock
import Definitions.Def_ChapterYangMillsHermite
import Definitions.Def_ChapterYangMillsFriedrichs
import Definitions.Def_ChapterHermiteProductCore
import Definitions.Def_ChapterFarisLavine
import Definitions.Def_ChapterDirectSumEsa
import Definitions.Def_ChapterTensorGraphCore
import Definitions.Def_ChapterSecondQuantizationCoreEsa
import Definitions.Def_ChapterYangMillsNonAbelianEsa
import Mathlib
import Definitions.Def_ChapterSmFockEsa
import Definitions.Def_ChapterSmHamiltonian
open BookProof.SmHamiltonian
open BookProof.SmFockEsa



open MvPolynomial
open BookProof.SmOneParticle BookProof.SmHamiltonian BookProof.SmOuterFock
open BookProof.YangMillsHermite BookProof.YangMillsFriedrichs
open BookProof.HermiteProductCore BookProof.FarisLavine BookProof.DirectSumEsa
open BookProof.TensorCore BookProof.SecondQuantizationCore
open BookProof.YangMillsNonAbelianEsa

noncomputable section

theorem BookProof.SmFockEsa.smSecMomIdx_injective (n : ℕ) : Function.Injective (smSecMomIdx n) := by sorry
