-- Generated from ChapterSmComparisonFull.lean — theorem BookProof.SmComparisonFull.sm_N_full_esa
import Definitions.Def_ChapterFarisLavine
import Definitions.Def_ChapterTensorSumChain
import Definitions.Def_ChapterSmComparison
import Definitions.Def_ChapterScalaronCoreEsa
import Definitions.Def_ChapterStoneBridge
import Definitions.Def_ChapterSirkTrotterKato
import Definitions.Def_ChapterEsaClosureCore
import Mathlib
import Definitions.Def_ChapterSmComparisonFull
import Definitions.Def_ChapterFarisLavineCore
open BookProof.SmComparisonFull



open BookProof.FarisLavine BookProof.TensorSumChain
open BookProof.SmComparison BookProof.ScalaronEsa
open BookProof.StoneBridge BookProof.ChapterStoneResolvent BookProof.EsaClosure
open MeasureTheory

noncomputable section

theorem BookProof.SmComparisonFull.sm_N_full_esa : EssentiallySelfAdjointOn smFullChain.dom smFullChain.op := by sorry
